         DO    ]HeatWave
Wave1    DFB   $a0,$a0,$a0,$a0,$a0,$a0,$a0,$a0,$a0,$a0,$a0
         DFB   $a0,$a0,$a0,$a0,$a0,$a0,$a0,$a0,$a0,$a0,$a0
Wave2    DFB   $a0,$a1,$a0,$a0,$a0,$a0,$a0,$a0,$a0,$9F,$a0
         DFB   $a0,$9F,$a0,$a0,$a0,$a0,$a0,$a0,$a0,$a1,$a0
Wave3    DFB   $a1,$a0,$a1,$a0,$a0,$a0,$a0,$a0,$9F,$a0,$9F
         DFB   $9F,$a0,$9F,$a0,$a0,$a0,$a0,$a0,$a1,$a0,$a1
Wave4    DFB   $a1,$a1,$a0,$a1,$a0,$a0,$a0,$9F,$a0,$9F,$9F
         DFB   $9F,$9F,$a0,$9F,$a0,$a0,$a0,$a1,$a0,$a1,$a1
Wave5    DFB   $a2,$a1,$a0,$a1,$a0,$a0,$a0,$9F,$a0,$9F,$9E
         DFB   $9E,$9F,$a0,$9F,$a0,$a0,$a0,$a1,$a0,$a1,$a2
Wave6    DFB   $a2,$a1,$a1,$a1,$a0,$a0,$a0,$9f,$9f,$9f,$9e ; 22 values x10
         DFB   $9e,$9f,$9f,$9f,$a0,$a0,$a0,$a1,$a1,$a1,$a2 ; = 220
         FIN
